#  Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
#  the License. A copy of the License is located at
#      http://aws.amazon.com/apache2.0/
#  or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and
#  limitations under the License.

---
AWSTemplateFormatVersion: '2010-09-09'
Description: Enables CloudTrail in Member Account and send logs to S3 bucket in Central
  log aggregator account
Metadata:
  License: Any code, applications, scripts, templates, proofs of concept, documentation
    and other items provided by AWS under this SOW are "AWS Content," as defined in
    the Agreement, and are provided for illustration purposes only. All such AWS Content
    is provided solely at the option of AWS, and is subject to the terms of the Addendum
    and the Agreement. Customer is solely responsible for using, deploying, testing,
    and supporting any code and applications provided by AWS under this SOW.
Parameters:
  AccountType:
    Type: String
    Description: "Enter the Account type Sandbox Prod NonProd"
  FACloudTrailS3BucketPrefix:
    Description: FA CloudTrail S3 Bucket Name Prefix.  Append Environment Name (nonprod/prod/sandbox)
    Type: String
Resources:
  CloudTrailLogGroup:
    Metadata:
      Use: Logging destination for CloudTrail Logs.
      Comments: Allows for the viewing/searching of the past 14 days of CloudTrail
        data from within the AWS Console.  Logs are archived in S3 by the CloudTrail
        for longer term storage.
    Properties:
      RetentionInDays: 365
    Type: AWS::Logs::LogGroup
  CloudTrailLogRole:
    Metadata:
      Use: IAM Role for CloudTrail to deliver logs to CloudWatch Logs.
      Comments: Only allows access to a specific log group and log-stream prefix.
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Sid: ''
        Version: '2012-10-17'
      Path: "/"
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogStream
            Effect: Allow
            Resource:
            - Fn::Sub: "${CloudTrailLogGroup.Arn}*"
            Sid: AWSCloudTrailCreateLogStream2014110
          - Action:
            - logs:PutLogEvents
            Effect: Allow
            Resource:
            - Fn::Sub: "${CloudTrailLogGroup.Arn}*"
            Sid: AWSCloudTrailPutLogEvents20141101
          Version: '2012-10-17'
        PolicyName: root
    Type: AWS::IAM::Role
  FACentralCloudTrailIngester:
    Type: AWS::CloudTrail::Trail
    Properties:
      CloudWatchLogsLogGroupArn:
        Fn::GetAtt:
        - CloudTrailLogGroup
        - Arn
      CloudWatchLogsRoleArn:
        Fn::GetAtt:
        - CloudTrailLogRole
        - Arn
      S3BucketName: !Join ['-',[!Ref FACloudTrailS3BucketPrefix,!Ref AccountType]]
      IsLogging: true
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
