#  Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
#  the License. A copy of the License is located at
#      http://aws.amazon.com/apache2.0/
#  or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
#  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and
#  limitations under the License.

# IAM Custom Roles Setup Template for the IFSB Basic Account 647323472008.
---

AWSTemplateFormatVersion: '2010-09-09'
Description: Creates IAM Roles, Groups and Polices for First American Organization Child Accounts
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W2001  # Ignore parameter not used warning

Parameters:
  # Roles
  InteractiveAccessRoleName:
    Type: String
    Description: Enter the name for the InteractiveAccess on IFSB Account
    Default: "Firstam_IFSB-N-2_InteractiveAccess"
  ProgrammaticAccessRoleName:
    Type: String
    Description: Enter the name for the ProgrammaticAccess on IFSB Account
    Default: "Firstam_IFSB-N-2_ProgrammaticAccess"
  ApplicationName:
    Description: Application Name associated to application to pass in as parameter into child resources
    Type: String
  EnvironmentName:
    Description: Environment Name for application to pass in as parameter into child resources
    Type: String
  ApplicationID:
    Description: Application ID number for the associated application to pass in as parameter into child resources
    Type: String
    MaxLength: 10
  AVMAccessLevel:
    Description: AVM Tag for the Access Level Control
    Type: String
  AVMAccessLevelRead:
    Description: AVM Tag for the Access Level Control
    Type: String
    Default: "CAVM-Read"

Resources:
  #----------------------------------------------------------------------------------------------
  # InfoSec team Interactive Access Role
  #----------------------------------------------------------------------------------------------
  InteractiveAccessRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: "Standard name is explicitly set to be mapped with Azure AD."       
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Federated:
            - !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/AzureADSync
          Action:
          - sts:AssumeRoleWithSAML
          Condition:
            StringEquals:
              SAML:aud: "https://signin.aws.amazon.com/saml"
      RoleName: !Ref InteractiveAccessRoleName
      MaxSessionDuration: 28800
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/AWSSupportAccess

  InteractiveAccessRoleTags:
    Type: "Custom::InteractiveAccessRoleTags"
    Properties:
      ServiceToken: !ImportValue 'ApplyTags-Lambda-Arn'
      ResourceType: 'AWS::IAM::Role'
      RoleName: !Ref InteractiveAccessRole
      Tags:
        - key: ApplicationID
          value: !Ref ApplicationID
        - key: ApplicationName
          value: !Ref ApplicationName
        - key: EnvironmentName
          value: !Ref EnvironmentName
        - key: AVMAccessLevel
          value: !Ref AVMAccessLevelRead
  #----------------------------------------------------------------------------------------------
  # InfoSec team Programmatic Access Role
  #----------------------------------------------------------------------------------------------
  ProgrammaticAccessRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F38
            reason: "Maximum permission is controlled through permissions boundary."          
          - id: W11
            reason: "Maximum permission is controlled through permissions boundary."
          - id: W28
            reason: "Standard name is explicitly set to be mapped with Azure AD."   
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Federated:
            - !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/AzureADSync
          Action:
          - sts:AssumeRoleWithSAML
          Condition:
            StringEquals:
              SAML:aud: "https://signin.aws.amazon.com/saml"
      RoleName: !Ref ProgrammaticAccessRoleName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
      PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/CAVM/FirstAm-GlobalPermissionsBoundary
      Policies:
      - PolicyName: !Sub "${ProgrammaticAccessRoleName}-Inline"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: AllowIAMBasicAccess
            Effect: Allow
            Action:
              ### Read
              - iam:Get*
              - iam:List*
              ### Tagging
              - iam:TagRole
              - iam:UntagRole
              ### EC2 permission
              - iam:CreateInstanceProfile
              - iam:AddRoleToInstanceProfile
              - iam:RemoveRoleFromInstanceProfile
              ### Update Role info
              - iam:UpdateRole
              - iam:UpdateRoleDescription
              ### Pass Role
              - iam:PassRole
              ### Delete Role
              - iam:DeleteRole
              ### Assume Role
              - sts:AssumeRoleWithSAML
              ### Create / Update / Delete Policy
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:CreatePolicyVersion
              - iam:DeletePolicyVersion
              - iam:DeleteInstanceProfile
              - iam:UpdateAssumeRolePolicy
            Resource: "*"
          ### Allow IAM Privilege Access with Permissions Boundary
          - Sid: AllowIAMAccess
            Effect: Allow
            Action:
              ### Create / Update Role
              - iam:CreateRole
              ### Attach Policy to Role
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PutRolePolicy
              - iam:PutRolePermissionsBoundary
              - iam:DeleteRole
              - iam:DeleteRolePolicy 
            Resource: "*"
            Condition:
              StringEquals:
                "iam:PermissionsBoundary": !Sub arn:aws:iam::${AWS::AccountId}:policy/CAVM/FirstAm-GlobalPermissionsBoundary
          ### DevOps Pipeline or Engineer should not update the Permissions Boundary
          - Sid: NoDevOpsPolicyEdit
            Effect: Deny
            Action:
              - iam:DeletePolicy
              - iam:CreatePolicy
              - iam:CreatePolicyVersion
              - iam:DeletePolicyVersion
              - iam:SetDefaultPolicyVersion
            Resource: 
              - !Sub "arn:aws:iam::${AWS::AccountId}:policy/CAVM/*"
          ### DevOps Pipeline or Enginner to delete existing Permissions Boundary
          - Sid: NoBoundaryRoleDelete
            Effect: Deny
            Action:
              - iam:DeleteRolePermissionsBoundary
            Resource:
              - !Join ['',['arn:aws:iam::', !Ref "AWS::AccountId", ':role/',!Ref ProgrammaticAccessRoleName]]     

  ProgrammaticAccessRoleTags:
    Type: "Custom::ProgrammaticAccessRoleTags"
    Properties:
      ServiceToken: !ImportValue 'ApplyTags-Lambda-Arn'
      ResourceType: 'AWS::IAM::Role'
      RoleName: !Ref ProgrammaticAccessRole
      Tags:
        - key: ApplicationID
          value: !Ref ApplicationID
        - key: ApplicationName
          value: !Ref ApplicationName
        - key: EnvironmentName
          value: !Ref EnvironmentName
        - key: AVMAccessLevel
          value: !Ref AVMAccessLevelRead
  #----------------------------------------------------------------------------------------------
Outputs:
  StackName:
      Description: Name of the current stack used for client CloudWatch Log Data Collection
      Value: !Ref 'AWS::StackName'
